### ISSUE TITLE
doubt

### ISSUE THREAD

**Issue by Vikas6584** [MC-HackerTech/Free-Nitro-Bot-by-MC-HackerTech#6]
Hello, 
How much time will it take to generate the free discord nitro code ?
and are these codes real, I mean can we use them to get Discord nitro for free ??

**Comment by MC-HackerTech** [comment]
Sorry for late response

**Comment by MC-HackerTech** [comment]
It will take can be long or short like from 1 - 10s or 1 - 5 minutes
